name: Gradle

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash    
    steps:
    - name: Skip non-ubuntu runners in ACT
      if: ${{ env.ACT && matrix.os != 'ubuntu-latest' }}
      run: exit 0
    - name: TB License
      run: |
        [ -z "${{secrets.TB_LICENSE}}" ] && exit 1
        mkdir -p ~/.vaadin/
        echo "${{secrets.TB_LICENSE}}" | jq -Rn 'input | split("/") as $parts | {username: $parts[0], proKey: $parts[1]}' > ~/.vaadin/proKey
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.vaadin
        key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties', 'gradle.properties') }}
    - name: Install Chrome Libs (ACT in linux)
      if: ${{ env.ACT && matrix.os == 'ubuntu-latest' }}
      run: npx playwright install --with-deps chrome
    - name: Build and Test with Gradle
      run: |
        ./gradlew --stacktrace --info --no-daemon clean build \
          -Pvaadin.productionMode -Pit \
          -Dcom.vaadin.testbench.Parameters.headless=true \
          -Dcom.vaadin.testbench.Parameters.chromeOptions=--no-sandbox
    - name: Publish Test Results
      if: ${{ !env.ACT && always() && runner.os == 'Linux' }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: build/test-results/**/TEST-*.xml
